import type { User, DutySchedule, Notification } from "./types"

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Nguyễn Văn Admin",
    email: "admin@school.edu.vn",
    role: "admin",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "2",
    name: "Trần Thị Lan",
    email: "lan.tran@school.edu.vn",
    role: "teacher",
    class: "12A1",
    phone: "0901234567",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "3",
    name: "Lê Minh Tuấn",
    email: "tuan.le@student.edu.vn",
    role: "student",
    class: "12A1",
    phone: "0987654321",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "4",
    name: "Phạm Thu Hương",
    email: "huong.pham@student.edu.vn",
    role: "student",
    class: "12A1",
    phone: "0912345678",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
]

export const mockDutySchedules: DutySchedule[] = [
  {
    id: "1",
    userId: "3",
    user: mockUsers[2],
    date: new Date("2024-12-20"),
    shift: "morning",
    location: "Cổng chính",
    task: "Kiểm tra đồng phục học sinh",
    status: "completed",
    notes: "Hoàn thành tốt",
    createdAt: new Date("2024-12-15"),
    updatedAt: new Date("2024-12-20"),
  },
  {
    id: "2",
    userId: "4",
    user: mockUsers[3],
    date: new Date("2024-12-21"),
    shift: "afternoon",
    location: "Thư viện",
    task: "Hỗ trợ quản lý thư viện",
    status: "scheduled",
    createdAt: new Date("2024-12-15"),
    updatedAt: new Date("2024-12-15"),
  },
  {
    id: "3",
    userId: "3",
    user: mockUsers[2],
    date: new Date("2024-12-22"),
    shift: "morning",
    location: "Sân trường",
    task: "Dọn dẹp sân trường",
    status: "scheduled",
    createdAt: new Date("2024-12-15"),
    updatedAt: new Date("2024-12-15"),
  },
]

export const mockNotifications: Notification[] = [
  {
    id: "1",
    userId: "3",
    title: "Nhắc nhở trực nhật",
    message: "Bạn có lịch trực vào ngày mai lúc 7:00 AM tại Cổng chính",
    type: "reminder",
    isRead: false,
    createdAt: new Date("2024-12-20"),
  },
  {
    id: "2",
    userId: "4",
    title: "Phân công trực mới",
    message: "Bạn được phân công trực thư viện vào chiều mai",
    type: "assignment",
    isRead: true,
    createdAt: new Date("2024-12-19"),
  },
]
